version: '0.1'

services:
  hadoop-master:
    build: 
      target: hadoop-master
    container_name: hadoop-master
    volumes:
      - ./NameNode/Data:/usr/local/hadoop/data/nameNode
      - ./KDC/keytabs:/etc/security/keytab/
    hostname: hadoop-master.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.4.10
    extra_hosts: &hosts
      hadoop-master.docker.net: 192.168.4.10
      hadoop-worker1.docker.net: 192.168.4.11
      hadoop-worker2.docker.net: 192.168.4.12
      hadoop-rmanager.docker.net: 192.168.4.13
      hadoop-history.docker.net: 192.168.4.15
      kdc-server.docker.net: 192.168.4.20
      hadoop-client.docker.net: 192.168.4.100
    restart: always
    depends_on:
      - kdc-server

  hadoop-worker1:
    build:
      target: hadoop-worker
    container_name: hadoop-worker1
    volumes:
      - ./Worker/Data1:/usr/local/hadoop/data/dataNode
      - ./KDC/keytabs:/etc/security/keytab/
    hostname: hadoop-worker1.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.4.11
    extra_hosts: *hosts
    depends_on:
      - hadoop-master
      - hadoop-rmanager

  hadoop-worker2:
    build: 
      target: hadoop-worker
    container_name: hadoop-worker2
    volumes:
      - ./Worker/Data2:/usr/local/hadoop/data/dataNode
      - ./KDC/keytabs:/etc/security/keytab/
    hostname: hadoop-worker2.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.4.12
    extra_hosts: *hosts
    depends_on:
      - hadoop-master
      - hadoop-rmanager
  
  hadoop-rmanager:
    build: 
      target: hadoop-rmanager
    container_name: hadoop-rmanager
    volumes:
      - ./KDC/keytabs:/etc/security/keytab/
    hostname: hadoop-rmanager.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.4.13
    extra_hosts: *hosts
    restart: always
    depends_on:
      - kdc-server
      - hadoop-master

  hadoop-history:
    build: 
      target: hadoop-history
    container_name: hadoop-history
    volumes:
      - ./KDC/keytabs:/etc/security/keytab/
    hostname: hadoop-history.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.4.15
    extra_hosts: *hosts
    depends_on:
      - hadoop-rmanager
      - hadoop-master
  
  kdc-server:
    build:
      target: hadoop-kdc-server
    volumes:
      - ./KDC/keytabs:/root/keytabs
    container_name: kdc-server
    hostname: kdc-server.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.4.20
    restart: always
    extra_hosts: *hosts

  hadoop-client:
    build:
      target: hadoop-client
    container_name: hadoop-client
    hostname: hadoop-client.docker.net
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./KDC/keytabs:/etc/security/keytab/
    networks:
      docker.net:
        ipv4_address: 192.168.4.100
    extra_hosts: *hosts
    depends_on:
      - hadoop-rmanager
      - hadoop-master

networks:
    docker.net:
      driver: bridge
      name: docker.net
      enable_ipv6: false    
      ipam:
        driver: default
        config:
          - subnet: 192.168.4.0/24

# TODO:
# исправить ссылки в Readme.md
# Перейти на Docker swarm
# ApacheRanger и ApacheKnox - попробовать настроить