services:
  ldap-server:
    build:
      target: ldap-server
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
    container_name: ldap-server
    hostname: ldap-server.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.9.31
    extra_hosts: &hosts
      ldap-server.docker.net: 192.168.9.31
      kdc-server.docker.net: 192.168.9.2
      hadoop-master.docker.net: 192.168.9.10
      hadoop-worker1.docker.net: 192.168.9.11
      hadoop-worker2.docker.net: 192.168.9.12
      hadoop-rmanager.docker.net: 192.168.9.13
      hadoop-history.docker.net: 192.168.9.15
      hadoop-solr.docker.net: 192.168.9.16
      hadoop-postgres.docker.net: 192.168.9.17
      hadoop-ranger.docker.net: 192.168.9.18
      hadoop-knox.docker.net: 192.168.9.19
      hadoop-client.docker.net: 192.168.9.100
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host1"
    
  kdc-server:
    build:
      target: kdc-server
    volumes:
      - ./Data/Sync:/etc/sync
      - ./Data/CA:/etc/CA
      - ./Data/KDC:/etc/security/
    container_name: kdc-server
    hostname: kdc-server.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.9.2
    extra_hosts: *hosts
    depends_on:
      - ldap-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host1"

  hadoop-master:
    build: 
      target: hadoop-master
    container_name: hadoop-master
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
      - ./Data/NameNode:/usr/local/hadoop/data/nameNode
    hostname: hadoop-master.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.9.10
    extra_hosts: *hosts
    depends_on:
      - kdc-server
      - hadoop-worker1
      - hadoop-worker2
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host1"

  hadoop-worker1:
    build:
      target: hadoop-worker
    container_name: hadoop-worker1
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
      - ./Data/Worker1:/usr/local/hadoop/data/dataNode
    hostname: hadoop-worker1.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.9.11
    extra_hosts: *hosts
    depends_on:
      - kdc-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host1"

  hadoop-worker2:
    build: 
      target: hadoop-worker
    container_name: hadoop-worker2
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
      - ./Data/Worker2:/usr/local/hadoop/data/dataNode
    hostname: hadoop-worker2.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.9.12
    extra_hosts: *hosts
    depends_on:
      - kdc-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host1"
        
  hadoop-rmanager:
    build: 
      target: hadoop-rmanager
    container_name: hadoop-rmanager
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
      # - ./Data/Ranger_distrib/ranger/target:/ranger/target
    hostname: hadoop-rmanager.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.9.13
    extra_hosts: *hosts
    depends_on:
      - kdc-server
      - hadoop-master
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host1"

  hadoop-history:
    build: 
      target: hadoop-history
    container_name: hadoop-history
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
    hostname: hadoop-history.docker.net
    networks:
      docker.net:
        ipv4_address: 192.168.9.15
    extra_hosts: *hosts
    depends_on:
      - hadoop-rmanager
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host1"
  
  hadoop-client:
    build:
      target: hadoop-client
    container_name: hadoop-client
    hostname: hadoop-client.docker.net
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
    networks:
      docker.net:
        ipv4_address: 192.168.9.100
    extra_hosts: *hosts
    depends_on:
      - kdc-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host2"
    
  ranger-distrib:
    build:
      target: ranger-distrib
    container_name: ranger-distrib
    hostname: ranger-distrib.docker.net
    volumes:
      - ./Data/Ranger_distrib/ranger:/ranger
      - ./Data/Ranger_distrib/.m2:/.m2
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host2"
      
  hadoop-postgres:
    image: postgres
    container_name: hadoop-postgres
    hostname: hadoop-postgres.docker.net
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Postgres:/var/lib/postgresql/data
      # https://hub.docker.com/_/postgres Initialization scripts
      - ./scripts/postgres/init-ranger-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./scripts/postgres/log-setting.sh:/docker-entrypoint-initdb.d/log-setting.sh
      - ./scripts/postgres/create-ssl-key.sh:/docker-entrypoint-initdb.d/init-ssl.sh
    networks:
      docker.net:
        ipv4_address: 192.168.9.17
    extra_hosts: *hosts
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host2"

  hadoop-solr:
    build: 
        target: hadoop-solr
    container_name: hadoop-solr
    hostname: hadoop-solr.docker.net
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
    networks:
      docker.net:
        ipv4_address: 192.168.9.16
    extra_hosts: *hosts
    depends_on:
      - kdc-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host2"

  hadoop-ranger:
    build: 
      target: hadoop-ranger
    container_name: hadoop-ranger
    hostname: hadoop-ranger.docker.net
    volumes:
      - ./Data/CA:/etc/CA
      - ./Data/KnoxPK:/etc/kpk
      - ./Data/Sync:/etc/sync
      - ./Data/KDC:/etc/security
    networks:
      docker.net:
        ipv4_address: 192.168.9.18
    extra_hosts: *hosts
    # ports:
    #   - "6182:6182"
    depends_on:
      - kdc-server
      - hadoop-postgres
      - hadoop-solr
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host2"

  hadoop-knox:
    build:
      target: hadoop-knox
    container_name: hadoop-knox
    hostname: hadoop-knox.docker.net
    ports:
      - "8443:8443"
    volumes:
      - ./Data/Sync:/etc/sync
      - ./Data/CA:/etc/CA
      - ./Data/KnoxPK:/etc/kpk
      - ./Data/KDC:/etc/security/
    networks:
      docker.net:
        ipv4_address: 192.168.9.19
    extra_hosts: *hosts
    depends_on:
      - kdc-server
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.TAG==host2"
 
networks:
    docker.net:
      driver: bridge
      name: docker.net
      # enable_ipv6: false    
      ipam:
        driver: default
        config:
          - subnet: 192.168.9.0/24

# xhost + ${localhost}

# TODO:
# исправить ссылки в Readme.md
# Перейти на Docker swarm
# настройка рейнджер-хдфс
# настройка рейнджер-ямл
# кнокс