CREATE USER rangeradmin WITH CREATEDB LOGIN;
ALTER USER rangeradmin WITH PASSWORD 'hadoop';
CREATE DATABASE ranger WITH OWNER rangeradmin;
GRANT ALL PRIVILEGES ON SCHEMA public TO rangeradmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rangeradmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rangeradmin;
